### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by LanceLake** [blackspherefollower/NogasmChart#11]
I am on Windows 10 home and I don't have a device plugged in. When I run the program, it attempts to load, but fails. Do I need a device plugged in before starting? If so, a suggestion would be to load up, but put on the screen that a device needs to be plugged in first.

**Comment by blackspherefollower** [comment]
It shouldn't need either a nogasm or an output device connected at startup. I wonder if there's no serial ports, it crashes when it can't find the first one? I don't suppose there's any info logged for the crash? I might see if I can get sentry crash reporting built in.

**Comment by LanceLake** [comment]
The only parts that I thought I needed was a USB. I don't think I have a
serial port on this computer. So not a serial port, but I have USB ports if
that helps.

**Comment by blackspherefollower** [comment]
The Arduino/Teensy that the Nogasm is based on will register as a serial port: serial over USB.

This is just a guess though, since I don't really have much to go on other than you don't have any hardware plugged in.

I'll test the guess and probably add some crash reporting later this week: I'm in the middle of a house move, so they'll be a bit of a delay.

**Comment by blackspherefollower** [comment]
@LanceLake I reproduced what I think might have been your crash, and fixed in in the 0.0.3 release.

I've also added crash reporting, so if it still crashes, you'll be able to send all the relevant information in a single click.
